### ISSUE TITLE
Option to "pressing" Enter key after typing

### ISSUE THREAD

**Issue by rizhenkov** [LedgerHQ/app-passwords#10]
Hi! This app may be pretty usefull for typing start-up password at encrypted servers (without attaching display and keyboard).
For that case we need to add option for typing "Enter" key after "typing" password.
It may be a great optional feature.

**Comment by TamtamHero** [comment]
Available in the settings from v1.0.0 (https://github.com/LedgerHQ/app-passwords/commit/8539f124f0c0a861ee1cbe1a9af251de5300af72)
