### ISSUE TITLE
Password manager crashes constantly after last update.

### ISSUE THREAD

**Issue by brutesque** [LedgerHQ/app-passwords#15]
Password manager won't type in the password anymore. The ui on the ledger will also lock-up, so disconnection is the only option. I've been using the pw manager happily but since the last firmware update it hardly works anymore. About 1 in 10 attempts actually work. So at the moment the app broke to an unusable level.

**Comment by brutesque** [comment]
I have som more specific information on the bug. I tried typing the password which failed as usual. I then went into the menu to add another password. After that one was added, I tried letting it type again and this time it actually worked.

**Comment by TamtamHero** [comment]
Sorry for the delay. Which OS ? Which app version ?

**Comment by lpascal-ledger** [comment]
Is this still the case? I've no seen any resembling behavior. We would need information on computre OS / device type / device OS version and app version please.

Will close in two weeks if no additional inputs.

**Comment by brutesque** [comment]
I've given up on the concept of using the ledger as a pw manager
