### ISSUE TITLE
Nano S password manager typing layout was changed

### ISSUE THREAD

**Issue by TheRealSoret** [LedgerHQ/app-passwords#16]
Hey, I have to say the current layout is terrible, is there a way to revert back to the more efficient layout? I really liked that one. Would it be possible to make it an option to use one via a selection screen?

**Comment by brutesque** [comment]
i disliked the previous one, although I recognise some people like it. +1 to make it an option.

**Comment by TamtamHero** [comment]
The previous layout is not supported anymore, which is very sad, but it was too confusing for some people so we discarded it.
If you want to add new passwords typed from your PC keyboard, it's now possible. Have a look here: https://github.com/LedgerHQ/app-passwords/pull/29
