### ISSUE TITLE
version 0.0.4 derivation change and source availability?

### ISSUE THREAD

**Issue by jeremyawon** [LedgerHQ/app-passwords#17]
in the current Makefile, APPVERSION_P=3 (meaning 0.0.3), but the ledger manager Password Manager is at 0.0.4.

is the 0.0.4 source available?

also, has the derivation from meta data algorithm changed? it seems so, and that leaves 0.0.3 users unable to upgrade.

**Comment by jeremyawon** [comment]
the issue turns out to be that the exact input-keyboard constraints chosen on entering a password name get saved as a hidden part of the derivation.

i.e., if you have the entry BLAH, and you choose "without lowercase" when creating the entry, the derived password will be different than if "with lowercase" was chosen.

choosing all character sets for the input-keyboard leads to derivations matching 0.0.3.

having this kind of hidden state in the meta data seems problematic. was this a deliberate decision?

**Comment by riordant** [comment]
@jeremyawon: It is absolutely insane to me that Ledger have not replied to you on this issue. Ironically was only able to reply to your comment after finally being able to readd my github password after several failed attempts (exact same metadata). If not for your comment I would have been left locked out of several accounts. No documentation from Ledger, no updates, nothing. Very poor form

**Comment by riordant** [comment]
FWIW, can confirm that selections of characters affects derivation.

**Comment by TamtamHero** [comment]
Backing up and restoring this app has always been a pain, that's why we state it's "alpha" quality.
Sorry for not responding to this issue, this app has been an orphan for a while but I've started maintaining it recently.
Have a look at https://github.com/LedgerHQ/app-passwords/pull/29 , it improves the situation for further updates.
