### ISSUE TITLE
password manager is typing complete garbage

### ISSUE THREAD

**Issue by 1989gironimo** [LedgerHQ/app-passwords#18]
For example:
The simple password "aA0" gets typed as "2tp/Mß VYKJ.eZAÜÖ-" with the keyboard layout QWERTY selected.
If I change to another keyboard layout, it doesn't get any better, just different characters and symbols.

Using Ubuntu 18.04
ledger nano s firmware 1.4.2

**Comment by riordant** [comment]
I think you're confused as to how this works - the password string you enter yourself is just a piece of metadata for the real password. The real password is derived from it, AND your mnemonic seed. This means that you can simply keep a (preferably secure) backup of the metadata that you enter into the device along with your seed, so you can restore every password should you break/lose your device.

**Comment by 1989gironimo** [comment]
Ok - got it. I couldn't find a good documentation about this feature, so this was not obvious to me.
Thanks for the clarification.
