### ISSUE TITLE
Enable bulk creation of new passwords

### ISSUE THREAD

**Issue by TheFrozenFire** [LedgerHQ/app-passwords#19]
I use a similar scheme to this password manager app already, and would like to migrate my passwords to its approach. I would like to provide a list of entries for which to generate passwords, and have the password manager type back out the passwords I'm generating rapidly.

I'll take a look at implementing this myself, but figured I'd put it out there for anyone else who might be interested in the feature.

**Comment by TheFrozenFire** [comment]
#20 might provide an avenue for this that doesn't require a manual protocol.

**Comment by TamtamHero** [comment]
https://github.com/LedgerHQ/app-passwords/pull/29
Using the backup/restore tool introduced with this release, importing a list of entries from somewhere else gets easier. Still need to put your hands in a JSON file but that's better than typing a hundred names with the Nano S virtual keyboard :smile:
