### ISSUE TITLE
Firmware version 1.5.5 ledger nano s killed the application

### ISSUE THREAD

**Issue by Rezovich** [LedgerHQ/app-passwords#22]
after upgrading the ledger nano s from 1.4.2 to 1.5.5, the password manager does not work. What to do? the application is installed but the password cannot be inserted

**Comment by Rezovich** [comment]
probably it at all? and need to wait for the update?

**Comment by TamtamHero** [comment]
I guess you were using Windows.
Just merged #29, 1.0.0 is now available on Ledger Live, and it should fix your issues.
There's a lot of novelty, especially the possibility to backup the list of passwords with https://blog.ledger.com/passwords-backup/
(Sadly, it won't work with the version currently installed on your device (<1.0.0), but from now on updates will be smooth)
Be careful when upgrading the app, backup all the password names manually !
