### ISSUE TITLE
Not able to install 1.0.1 on Nano S

### ISSUE THREAD

**Issue by fti7** [LedgerHQ/app-passwords#31]
I tried to update/install the new 1.0.1 on an Nano S
Ledger Live shows that has been successfully installed on the Device. But its not shown in the Device Menu.
Also when im closing/reopen Ledger Live, i able to install the App again.

No Error Message or something.

![image](https://user-images.githubusercontent.com/7014664/103600084-e8db0d00-4f06-11eb-8358-72a7812e650a.png)

Tried with Ledger Live on Windows + Android, same behavior

```
	{
		"type": "cmd.START",
		"data": {
			"appOp": {
				"type": "install",
				"name": "Passwords"
			},
			"targetId": 823132164,
			"app": {
				"id": 7842,
				"name": "Passwords",
				"version": "1.0.1",
				"description": "",
				"dateModified": "2021-01-04T13:22:13.338795Z",
				"icon": "passwords",
				"authorName": null,
				"supportURL": null,
				"contactURL": null,
				"sourceURL": null,
				"compatibleWallets": [

				],
				"hash": "4344e7fc2fbb7ae696a9a2dafd3d171549ecbd6f56ffcf96b0ed9578ef2ede85",
				"perso": "perso_11",
				"firmware": "nanos/1.6.1-2/pwmgr/app_1.0.1",
				"firmware_key": "nanos/1.6.1-2/pwmgr/app_1.0.1_key",
				"delete": "nanos/1.6.1-2/pwmgr/app_1.0.1_del",
				"delete_key": "nanos/1.6.1-2/pwmgr/app_1.0.1_del_key",
				"dependencies": [

				],
				"bytes": 34824,
				"warning": null,
				"indexOfMarketCap": -1,
				"isDevTools": true
			},
			"deviceId": ""
		},
		"level": "info",
		"message": "CMD appOpExec.send()",
		"pname": "renderer",
		"timestamp": "2021-01-05T02:29:54.137Z"
    },,,
`

**Comment by TamtamHero** [comment]
I just tried and had no issue, both on nano X/S.
There are some issues with the Ledger Live Manager, sometimes it instantly installs an app (but it actually doesn't), there's investigations on that. For the time being, keep trying until it works :unamused:
