### ISSUE TITLE
new USB backend - Chrome Flag is missing

### ISSUE THREAD

**Issue by Kf-VasileMoraru** [LedgerHQ/app-passwords#39]
From ledgerhq.github.io/passwords-backup, i am advised to "you need to first go to chrome://flags then search for Enable new USB backend, disable it and relaunch Chrome." 

Unfortunately, this flag "USB backend" is missing in google Chrome.

I can not use https://ledgerhq.github.io/passwords-backup/,

How can i find - USB backend

**Comment by monperrus** [comment]
I confirm that I cannot use the backup web app on Chrome 108.

Using an old version of Chrome seems very unsecure.

@lpascal-ledger any plan to update the  backup web app?

that would be great, thanks!

**Comment by monperrus** [comment]
for the record, https://github.com/LedgerHQ/passwords-backup/pull/4 is a tentative pull-request to fix this problem.
