### ISSUE TITLE
Feature request - password backup

### ISSUE THREAD

**Issue by SeekerFS** [LedgerHQ/app-passwords#55]
Every time i update my firmware i lose all my password and i have to re-add them al over again.
Is it possible to add feature for a backup? when used it would export a list of my password names to a file on my computer, and after the firmware update i could recover them...?

**Comment by lpascal-ledger** [comment]
Hey :wave: 

There's a tool allowing that indeed, allow to backup to / restore from a JSON file.

Sources are [here](https://github.com/LedgerHQ/passwords-backup).
Web app [here](https://ledgerhq.github.io/passwords-backup/).

Hope it'll help!
