### ISSUE TITLE
W7 PC Locks Up Ledger without entering password?

### ISSUE THREAD

**Issue by jhoff80** [LedgerHQ/app-passwords#8]
I'm sure this is probably specific to my work PC, I doubt it's universal.  But for some reason when I try to use the Password Manager app on my work PC, which runs Windows 7, it just freezes the Ledger without typing in a password.  I know I've read somewhere that it's recommended to use USB 2.0 ports with the Ledger, but this PC only has USB 3.0.

**Comment by TamtamHero** [comment]
v1.0.0 fixes Windows support (read https://github.com/LedgerHQ/app-passwords/pull/29 before updating)
