### ISSUE TITLE
Impossible to type anything from the keyboard on the device.

### ISSUE THREAD

**Issue by gabridome** [LedgerHQ/app-passwords#9]
Ver 0.0.3,
Host Mac OS High Sierra (but also the preceding one).

When I want to add a "new password" (actually the first one), the program show on the device a keyboard in which it seems possible to select the characters to choose the name associated with the password.

When I press either two of the buttons I obtain inexplicable results that all of a sudden provoke the closing of the program with an unexpected result for the name of the password.

What I would expect is to be able to type in the name of the service for which I'm creating the password on the device.

I have asked an other guy to install the program on an other Mac with an other Ledger and the result is the same.

**Comment by zavan** [comment]
The keyboard is quite simple actually: It shows you 2 sets of letters, using one of the two buttons you choose the set that contains the letter you want, it will show two new sets (the one you chose previously divided in two), you choose the set that contains the letter you want, keep doing this until it's up to two letters, choose the one you want and it's typed.

**Comment by TamtamHero** [comment]
This binary keyboard has been confusing to many other users, we've discarded it :disappointed:
